version: '3.1'

services:
  securesql:
    build: ./sql
    image: securesql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - lsio
  secureapache:
    build: ./apache
    image: secureapache
    networks:
      - lsio
    ports:
       - "8003:80"

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8005:80"
    networks:
      - lsio
    links:
      - "securesql:db"

networks:
  lsio:
    external: true

